name: Test

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose

    - name: Build and Test
      run: |
        export DJANGO_SETTINGS_MODULE=application.settings
        docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py makemigrations --noinput && python manage.py migrate && python manage.py test"
    

